#!/bin/bash

BACKLIGHT_NOW=`cat /sys/class/leds/samsung\:\:kbd_backlight/brightness`
BACKLIGHT_MAX=`cat /sys/class/leds/samsung\:\:kbd_backlight/max_brightness`
CPUFREQ=`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor`

SINK_NAME="alsa_output.pci-0000_00_1b.0.analog-stereo"
VOL_MAX="65537"
VOL_STEP="3276"

VOL_NOW=`pacmd dump | grep -P "^set-sink-volume $SINK_NAME\s+" | perl -p -i -e 's/.+\s(.x.+)$/$1/'`


case $1 in
	bl+)
	BLC=$((BACKLIGHT_NOW+1))
	if [ $BLC -gt $((BACKLIGHT_MAX)) ]
	then
		BLC=$BACKLIGHT_MAX
	fi
	echo $BLC > /sys/class/leds/samsung\:\:kbd_backlight/brightness 
	;;

	bl-)
	BLC=$((BACKLIGHT_NOW-1))
	if [ $BLC -lt $((0)) ]
	then
		BLC=0
	fi
	echo $BLC > /sys/class/leds/samsung\:\:kbd_backlight/brightness
	;;
	swgov)
	if [ $CPUFREQ == "ondemand" ]
	then
		echo "powersave" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor		
		echo "powersave" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor		
		echo "powersave" > /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor		
		echo "powersave" > /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor
		notify-send "powersave"
	else
		echo "ondemand" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor		
		echo "ondemand" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor		
		echo "ondemand" > /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor		
		echo "ondemand" > /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor
		notify-send "ondemand"

	fi
	;;

	vol+)
	VOL_NEW=$((VOL_NOW + VOL_STEP))
	if [ $VOL_NEW -gt $((0x10000)) ]
	then
		VOL_NEW=$((0x10000))
	fi
	pactl set-sink-volume $SINK_NAME `printf "0x%X" $VOL_NEW`
	;;
	
	vol-)
											VOL_NEW=$((VOL_NOW - VOL_STEP))
	if [ $(($VOL_NEW)) -lt $((0x00000)) ]
	then
		VOL_NEW=$((0x00000))
	fi
	pactl set-sink-volume $SINK_NAME `printf "0x%X" $VOL_NEW`
	;;

	mute)

											MUTE_STATE=`pacmd dump | grep -P "^set-sink-mute $SINK_NAME\s+" | perl -p -i -e 's/.+\s(yes|no)$/$1/'`
	if [ $MUTE_STATE = no ]
	then
	        pactl set-sink-mute $SINK_NAME 1
			notify-send "muted"
	elif [ $MUTE_STATE = yes ]
	then
		pactl set-sink-mute $SINK_NAME 0
		notify-send "unmuted"
	fi
esac
